name             'liferay-stack'
maintainer       'Adam Krone'
maintainer_email 'adam.krone@thirdwavellc.com'
license          'Apache v2.0'
description      'Installs/Configures liferay-stack'
long_description 'Installs/Configures liferay-stack'
version          '1.1.0'

depends 'apt'
depends 'yum'
depends 'unzip'
depends 'ssh-import-id'
depends 'capistrano-base'
depends 'liferay'
